name: MBM | make your ideas work
work: Software Development & ICT Consulting

safe:        true
auto:        true
server:      false
server_port: 4000
base_url: "http://vanhonit.github.io/vanhonit/"

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
#markdown: rdiscount
pygments: true

#exclude: ['lib']
